In [1]:
import pandas as pd

In [2]:
df_survey = pd.read_csv(
    '../files/survey_results_public.csv', index_col='Respondent')

In [3]:
df_schema = pd.read_csv(
    '../files/survey_results_schema.csv', index_col='Column')

In [4]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 100)

In [5]:
df_survey

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [6]:
filter_high_salary = df_survey['ConvertedComp'] > 70000

In [7]:
df_survey.loc[filter_high_salary]

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,MongoDB,MariaDB;MySQL;Redis,"Developer, back-end;Developer, desktop or ente...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Remote work options;Opportunities for professi...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",JavaScript,Python;SQL,Unity 3D,Ansible,NaN,Confluence;Jira;Github;Slack;Microsoft Teams;G...,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Linux-based,20 to 99 employees,iOS;Slack Apps and Integrations,Docker,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,GBP,NaN,PostgreSQL,"Database administrator;Developer, back-end;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,Industry that I’d be working in;Diversity of t...,Very satisfied,"I’m not actively looking, but I am open to new...",Go,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,NaN,NaN,NaN,"Github;Slack;Google Suite (Docs, Meet, etc);St...",No,Extremely important,Fairly important,Having a bad day (or week or month) at work;Cu...,Personal network - friends or family;Directly ...,Once a year,Not sure,Yes,No,Often: 1-2 days per week or more,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"Just me - I am a freelancer, sole proprietor, ...",NaN,AWS;Docker;Google Cloud Platform;Heroku;Kubern...,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Multiple times per day,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,Cassandra;Elasticsearch;MariaDB;PostgreSQL;Redis,Microsoft SQL Server;PostgreSQL,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Industry that I’d be working in;Languages, fra...",Slightly dissatisfied,"I’m not actively looking, but I am open to new...",C#;Go;Haskell;HTML/CSS;JavaScript;Python;Ruby;...,C#;HTML/CSS;JavaScript;Python;SQL;VBA,.NET Core;Teraform,.NET;Node.js,"Github;Gitlab;Slack;Google Suite (Docs, Meet, ...",Github;Gitlab;Slack;Microsoft Teams;Google Sui...,Yes,Extremely important,Fairly important,Having a bad day (or week or month) at work;Be...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,No,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,20 to 99 employees,Docker;Kubernetes;Microsoft Azure,NaN,I have little or no influence,Straight / Heterosexual,Yes,"No, not at all",I have never participated in Q&A on Stack Over...,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,USD,Elasticsearch;PostgreSQL;Redis;SQLite,Elasticsearch;MariaDB;MySQL;Redis;SQLite,"Developer, back-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,I am not interested in new job opportunities,HTML/CSS;Perl,Bash/Shell/PowerShell;HTML/CSS;Perl,NaN,NaN,Github,Github;Slack,Not sure,Neutral,Very important,Looking to relocate,NaN,Once every few years,Yes,Onboarding? What onboarding?,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Do other work ...,Linux-based,100 to 499 employees,Linux,AWS;Linux,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",I have never participated in Q&A on Stack Over...,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
19,I am a developer by profession,No,24.0,15,Yearly,83400.0,83400.0,United States,United States dollar,USD,MariaDB;MongoDB,MariaDB;Microsoft SQL Server,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",C#;Go;Python;TypeScript,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...,Node.js;React Native;Unity 3D;Unreal Engine,.NET;.NET Core;Node.js,Github;Slack,Confluence;Jira;Github;Slack,Yes,Extremely important,Fairly important,Having a bad day (or week or month) at work;Tr...,Company reviews from third party sites (e.g. G...,Once a year,Yes,No,No,Occasionally: 1-2 days per quarter but less th...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,"10,000 or more employees",iOS;Slack Apps and Integrations,Windows,I have little or no influence,Straight / Heterosexual,Yes,Neutral,Less than once per month or monthly,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65586,I am a developer by profession,Yes,NaN,8,Yearly,225000.0,225000.0,United States,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, desktop or ente...",Some college/university study without earning ...,Employed full-time,NaN,NaN,NaN,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not sure,Extremely important,Very important,NaN,NaN,NaN,NaN,Yes,NaN,Sometimes: 1-2 days per month but less than we...,NaN,NaN,NaN,NaN,NaN,"1,000 to 4,999 employees",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mathematics or statistics,NaN,NaN,NaN,50.0,25,15
65589,I am a developer by profession,Yes,NaN,16,Yearly,150000.0,150000.0,United States,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Somewhat important,Fairly important,NaN,NaN,NaN,NaN,Onboarding? What onboarding?,NaN,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,NaN,NaN,NaN,20 to 99 employees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,45.0,10,6
65602,"I am not primarily a developer, but I write co...",Yes,NaN,13,Yearly,140000.0,140000.0,United States,United States dollar,USD,NaN,NaN,Data or business analyst;Data scientist or mac...,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fairly important,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,000 or more employees",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,15,12
65604,I am a developer by profession,No,NaN,13,Weekly,3000.0,150000.0,United States,United States dollar,USD,NaN,NaN,Academic researcher;Scientist,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,Slightly satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Somewhat important,Critically important,NaN,NaN,NaN,NaN,Yes,NaN,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,NaN,NaN,NaN,"10,000 or more employees",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,45.0,7,4
65617,I am a developer by profession,Yes,NaN,15,Yearly,120000.0,129718.0,Germany,European Euro,EUR,NaN,NaN,"Database administrator;Developer, back-end;Dev...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,Very satisfied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Extremely important,Very important,NaN,NaN,NaN,Not sure,Onboarding? What onboarding?,Yes,Often: 1-2 days per week or more,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,"Just me - I am a freelancer, sole proprietor, ...",NaN,NaN,NaN,NaN,Yes,Neutral,Less than once per month or monthly,Daily or almost daily,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,35.0,9,9

In [8]:
df_survey.loc[filter_high_salary].sort_values(
    by='ConvertedComp', ascending=False)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
29260,I am a developer by profession,Yes,51.0,16,Weekly,172000.0,2000000.0,United States,United States dollar,USD,Elasticsearch;IBM DB2;Microsoft SQL Server;Mon...,IBM DB2;Microsoft SQL Server;MongoDB;MySQL;SQLite,"Designer;Developer, back-end;Developer, deskto...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Woman,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;C++;HTML/CSS;Java;JavaSc...,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...,Apache Spark;Node.js;Unreal Engine,Node.js,Jira;Github;Gitlab;Microsoft Teams;Google Suit...,Jira;Github;Microsoft Teams;Google Suite (Docs...,Yes,Somewhat important,Very important,Better work/life balance;Wanting to work with ...,"Read company media, such as employee blogs or ...",NaN,Yes,No,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,"1,000 to 4,999 employees",Android;AWS;Docker;Kubernetes;Linux;Microsoft ...,Docker;Kubernetes;Linux;Microsoft Azure;Windows,I have some influence,Straight / Heterosexual,Yes,Neutral,I have never participated in Q&A on Stack Over...,Less than once per month or monthly,Easy,Appropriate in length,No,Mathematics or statistics,Angular;ASP.NET;Express;jQuery;React.js,Angular;ASP.NET;Express;jQuery,Just as welcome now as I felt last year,52.0,28,25
33865,I am a developer by profession,Yes,35.0,15,Monthly,250000.0,2000000.0,United States,United States dollar,USD,MongoDB;Redis,MongoDB;PostgreSQL;Redis,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Go;Python;TypeScript,Bash/Shell/PowerShell;Go;Java;JavaScript;Pytho...,Node.js;Teraform,Node.js;Teraform,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",Confluence;Jira;Github;Slack;Trello;Google Sui...,Not sure,Neutral,Somewhat important,Better compensation;Trouble with my teammates;...,"Read company media, such as employee blogs or ...",Once a year,Not sure,No,Yes,Sometimes: 1-2 days per month but less than we...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,100 to 499 employees,Arduino;AWS;Docker;Kubernetes;Linux;MacOS;Slac...,Arduino;AWS;Docker;Kubernetes;Linux;MacOS;Slac...,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",React.js,React.js;Vue.js,Just as welcome now as I felt last year,40.0,20,15
16018,I am a developer by profession,Yes,23.0,18,Weekly,82000.0,2000000.0,United States,United States dollar,USD,NaN,PostgreSQL;Redis,"Developer, back-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,Flex time or a flexible schedule;Remote work o...,Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;Python;Swift,Java,.NET Core;Node.js,NaN,Github,Confluence;Jira,Not sure,Neutral,Very important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Once every few years,Not sure,Yes,No,Never,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,"1,000 to 4,999 employees",iOS;Linux;MacOS;Raspberry Pi,Docker;Linux,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Easy,Too long,No,"Computer science, computer engineering, or sof...",ASP.NET Core,jQuery,Just as welcome now as I felt last year,40.0,5,1
193,I am a developer by profession,Yes,29.0,16,Weekly,120000.0,2000000.0,United States,United States dollar,USD,NaN,NaN,"Developer, mobile","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Specific department or team I’d be working on;...,Very satisfied,"I’m not actively looking, but I am open to new...",Objective-C;Swift,Java;JavaScript;Objective-C;Swift,NaN,NaN,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",Github;Gitlab;Slack;Microsoft Teams;Trello;Goo...,No,Neutral,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Every few months,No,Onboarding? What onboarding?,No,Never,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Do other work ...,MacOS,10 to 19 employees,Android;iOS,Android;iOS,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,A few times per week,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,13,7
3948,I am a developer by profession,Yes,25.0,18,Weekly,70000.0,2000000.0,United States,United States dollar,USD,MariaDB;MongoDB;Redis,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...,Data or business analyst;Data scientist or mac...,"Secondary school (e.g. American high school, G...",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,"I’m not actively looking, but I am open to new...",Dart;Go;HTML/CSS;JavaScript;Rust;TypeScript,Assembly;C;C#;C++;HTML/CSS;Java;JavaScript;PHP...,Flutter;Hadoop;Node.js;React Native;TensorFlow...,.NET;.NET Core;Cordova;Hadoop;Node.js;React Na...,Github;Gitlab;Microsoft Teams;Microsoft Azure;...,Github;Gitlab;Microsoft Teams;Microsoft Azure,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Growth or le...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,Yes,Often: 1-2 days per week or more,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Watch help / tutorial videos,Windows,500 to 999 employees,Kubernetes;Linux;Microsoft Azure;Windows,Android;Arduino;Docker;Google Cloud Platform;H...,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Express;React.js;Vue.js,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,NaN,40.0,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21657,I am a developer by profession,Yes,19.0,12,Monthly,5400.0,70044.0,Germany,European Euro,EUR,MariaDB;Microsoft SQL Server;MySQL,MariaDB;Microsoft SQL Server;MySQL,"Database administrator;Developer, back-end;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Diversity of the company or organization;Langu...,Very satisfied,I am not interested in new job opportunities,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;PHP,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;PHP,.NET;.NET Core;TensorFlow,.NET;.NET Core;TensorFlow,NaN,NaN,Not sure,Neutral,Somewhat important,Trouble with my direct manager;Trouble with le...,"Read company media, such as employee blogs or ...",Once every few years,No,Yes,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Linux-based,10 to 19 employees,Arduino;Linux;Windows,Arduino;Docker;Linux;Windows;WordPress,I have a great deal of influence,NaN,Yes,Not sure,Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core,ASP.NET;jQuery,A lot less welcome now than last year,60.0,7,3
29429,I am a developer by profession,Yes,33.0,10,Monthly,20000.0,70044.0,Israel,Israeli new shekel,ILS,Elasticsearch;Firebase;MySQL;Redis,MySQL,Data scientist or machine learning specialist;...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Middle Eastern;White or of European descent,Man,Flex time or a flexible schedule;Specific depa...,Slightly satisfied,I am not interested in new job opportunities,Python,Bash/Shell/PowerShell;Ruby,Apache Spark;Hadoop;Keras;Pandas;TensorFlow;To...,NaN,"Jira;Github;Slack;Google Suite (Docs, Meet, etc)","Jira;Github;Slack;Google Suite (Docs, Meet, etc)",Yes,Somewhat important,Very important,Just because;Curious about other opportunities...,Company reviews from third party sites (e.g. G...,Once a year,No,No,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Meditate;Call a coworker or friend;Visit Stack...,MacOS,"1,000 to 4,999 employees",Docker;Google Cloud Platform;Linux;MacOS,Linux;MacOS,I have some influence,Straight / Heterosexual,No,"No, not really",NaN,Daily or almost daily,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",NaN,Ruby on Rails,Just as welcome now as I felt last year,45.0,15,10
44018,I am a developer by profession,Yes,42.0,17,Monthly,2200.0,70020.0,Bahrain,Bahraini dinar,BHD,Elasticsearch;IBM DB2;MariaDB;Microsoft SQL Se...,IBM DB2;Microsoft SQL Server;Oracle;Redis,"Designer;Developer, back-end;Developer, deskto...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,Remote work options;Office environment or comp...,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",C#;C++;HTML/CSS;JavaScript;SQL;TypeScript,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;JavaSc...,.NET;.NET Core;Flutter;Node.js;React Native;Te...,.NET;.NET Core,Jira;Github;Microsoft Teams;Microsoft Azure,Jira;Github;Gitlab;Microsoft Teams,No,Extremely important,Very important,Wanting to share accomplishments with a wider ...,"Read company media, such as employee blogs or ...",Every few months,Not sure,Onboarding? What onboarding?,No,Rarely: 1-2 days per year or less,NaN,Indifferent,Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,20 to 99 employees,AWS;Docker;Kubernetes;Linux;Microsoft Azure;Wi...,Docker;Linux;Windows,I have little or no influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per week,Daily or almost daily,NaN,NaN,No,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery;React.js;Vue.js,ASP.NET;ASP.NET Core;jQuery,Just as welcome now as I felt last year,40.0,20,18
5459,I am a developer by profession,Yes,31.0,NaN,Yearly,104800.0,70017.0,Australia,Australian dollar,AUD,Microsoft SQL Server;MongoDB;Oracle,Oracle,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,How widely used or impactful my work output wo...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",C#;JavaScript;Python;TypeScript,C#;JavaScript,.NET Core;Node.js,.NET Core,Confluence;Github;Microsoft Azure,Microsoft Azure,No,Extremely important,Fairly important,Having a bad day (or week or month) at work;Wa...,Company reviews from third party sites (e.g. G...,Once a year,NaN,No,Yes,Sometimes: 1-2 days per month but less than we...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,NaN,Docker;Microsoft Azure;Windows,Microsoft Azure;Windows,I have little or no influence,Straight / Heterosexual,Not sure/can't remember,"No, not really",NaN,Daily or almost daily,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",ASP.NET Core;React.js,ASP.NET;ASP.NET Core;React.js,NaN,40.0,10,10
58883,I am a developer by profession,Yes,NaN,12,Yearly,70008.0,70008.0,United States,United States dollar,USD,Firebase;MongoDB,Microsoft SQL Server,"Developer, desktop or enterprise applications;...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Industry that I’d be working in;Languages, fra...",Slightly dissatisfied,I am actively looking for a job,C#;Kotlin;Python,C#;Java;JavaScript;Python;SQL,.NET;.NET Core;Unity 3D,.NET;.NET Core;Unity 3D,"Github;Google Suite (Docs, Meet, etc);Stack Ov...","Github;Microsoft Teams;Google Suite (Docs, Mee...",Not sure,Extremely important,Fairly important,Having a bad day (or week or month) at work;Cu...,Company reviews from third party sites (e.g. G...,Once a year,No,Yes,Yes,Rarely: 1-2 days per year or less,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Meditate;Play games;Visit Stack Overflow;Go fo...,Windows,100 to 499 employees,Android;Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Raspberry Pi;Windows,I have little or no influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,Easy,Too short,No,"Computer science, computer engineering, or sof...",ASP.NET Core;React.js,Angular.js;ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,40.0,12,4

In [9]:
df_survey.loc[filter_high_salary].sort_values(
    by='ConvertedComp', ascending=False).head(10)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
29260,I am a developer by profession,Yes,51.0,16,Weekly,172000.0,2000000.0,United States,United States dollar,USD,Elasticsearch;IBM DB2;Microsoft SQL Server;Mon...,IBM DB2;Microsoft SQL Server;MongoDB;MySQL;SQLite,"Designer;Developer, back-end;Developer, deskto...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Woman,"Flex time or a flexible schedule;Languages, fr...",Very satisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;C++;HTML/CSS;Java;JavaSc...,Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;Java;J...,Apache Spark;Node.js;Unreal Engine,Node.js,Jira;Github;Gitlab;Microsoft Teams;Google Suit...,Jira;Github;Microsoft Teams;Google Suite (Docs...,Yes,Somewhat important,Very important,Better work/life balance;Wanting to work with ...,"Read company media, such as employee blogs or ...",NaN,Yes,No,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow...,Windows,"1,000 to 4,999 employees",Android;AWS;Docker;Kubernetes;Linux;Microsoft ...,Docker;Kubernetes;Linux;Microsoft Azure;Windows,I have some influence,Straight / Heterosexual,Yes,Neutral,I have never participated in Q&A on Stack Over...,Less than once per month or monthly,Easy,Appropriate in length,No,Mathematics or statistics,Angular;ASP.NET;Express;jQuery;React.js,Angular;ASP.NET;Express;jQuery,Just as welcome now as I felt last year,52.0,28,25
33865,I am a developer by profession,Yes,35.0,15,Monthly,250000.0,2000000.0,United States,United States dollar,USD,MongoDB;Redis,MongoDB;PostgreSQL;Redis,"Developer, back-end;Developer, front-end;Devel...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Go;Python;TypeScript,Bash/Shell/PowerShell;Go;Java;JavaScript;Pytho...,Node.js;Teraform,Node.js;Teraform,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",Confluence;Jira;Github;Slack;Trello;Google Sui...,Not sure,Neutral,Somewhat important,Better compensation;Trouble with my teammates;...,"Read company media, such as employee blogs or ...",Once a year,Not sure,No,Yes,Sometimes: 1-2 days per month but less than we...,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,100 to 499 employees,Arduino;AWS;Docker;Kubernetes;Linux;MacOS;Slac...,Arduino;AWS;Docker;Kubernetes;Linux;MacOS;Slac...,I have little or no influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",React.js,React.js;Vue.js,Just as welcome now as I felt last year,40.0,20,15
16018,I am a developer by profession,Yes,23.0,18,Weekly,82000.0,2000000.0,United States,United States dollar,USD,NaN,PostgreSQL;Redis,"Developer, back-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,Man,Flex time or a flexible schedule;Remote work o...,Slightly satisfied,"I’m not actively looking, but I am open to new...",C#;Python;Swift,Java,.NET Core;Node.js,NaN,Github,Confluence;Jira,Not sure,Neutral,Very important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Once every few years,Not sure,Yes,No,Never,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,"1,000 to 4,999 employees",iOS;Linux;MacOS;Raspberry Pi,Docker;Linux,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,Daily or almost daily,Easy,Too long,No,"Computer science, computer engineering, or sof...",ASP.NET Core,jQuery,Just as welcome now as I felt last year,40.0,5,1
193,I am a developer by profession,Yes,29.0,16,Weekly,120000.0,2000000.0,United States,United States dollar,USD,NaN,NaN,"Developer, mobile","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,White or of European descent,Man,Specific department or team I’d be working on;...,Very satisfied,"I’m not actively looking, but I am open to new...",Objective-C;Swift,Java;JavaScript;Objective-C;Swift,NaN,NaN,"Github;Slack;Trello;Google Suite (Docs, Meet, ...",Github;Gitlab;Slack;Microsoft Teams;Trello;Goo...,No,Neutral,Fairly important,Curious about other opportunities;Better compe...,"Read company media, such as employee blogs or ...",Every few months,No,Onboarding? What onboarding?,No,Never,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Play games;Visit Stack Overflow;Do other work ...,MacOS,10 to 19 employees,Android;iOS,Android;iOS,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,A few times per week,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,13,7
3948,I am a developer by profession,Yes,25.0,18,Weekly,70000.0,2000000.0,United States,United States dollar,USD,MariaDB;MongoDB;Redis,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...,Data or business analyst;Data scientist or mac...,"Secondary school (e.g. American high school, G...",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Very satisfied,"I’m not actively looking, but I am open to new...",Dart;Go;HTML/CSS;JavaScript;Rust;TypeScript,Assembly;C;C#;C++;HTML/CSS;Java;JavaScript;PHP...,Flutter;Hadoop;Node.js;React Native;TensorFlow...,.NET;.NET Core;Cordova;Hadoop;Node.js;React Na...,Github;Gitlab;Microsoft Teams;Microsoft Azure;...,Github;Gitlab;Microsoft Teams;Microsoft Azure,Yes,Extremely important,Not at all important/not necessary,Curious about other opportunities;Growth or le...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,Yes,Often: 1-2 days per week or more,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Watch help / tutorial videos,Windows,500 to 999 employees,Kubernetes;Linux;Microsoft Azure;Windows,Android;Arduino;Docker;Google Cloud Platform;H...,I have some influence,Straight / Heterosexual,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Express;React.js;Vue.js,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,NaN,40.0,6,3
33787,I am a developer by profession,Yes,28.0,11,Weekly,120000.0,2000000.0,United States,United States dollar,USD,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL;...,Cassandra;Microsoft SQL Server;MongoDB;MySQL;P...,Data or business analyst;Data scientist or mac...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Remote work options;Financial performance or f...,Very satisfied,"I’m not actively looking, but I am open to new...",C;Python;Rust;SQL,C;Python;SQL,Pandas;Teraform,Hadoop;Pandas;Teraform,Github;Gitlab,Confluence;Jira;Github;Gitlab;Slack;Microsoft ...,No,Extremely important,Fairly important,Wanting to work with new technologies;Growth o...,"Read company media, such as employee blogs or ...",Once a year,NaN,Onboarding? What onboarding?,Yes,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Go for a walk or oth...,Linux-based,20 to 99 employees,AWS;Docker;Google Cloud Platform;Kubernetes;Linux,AWS;Docker;Google Cloud Platform;Kubernetes;Linux,I have some influence,Straight / Heterosexual,Yes,"No, not really",Less than once per month or monthly,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,55.0,10,3
4027,I am a developer by profession,Yes,29.0,16,Weekly,120000.0,2000000.0,United States,United States dollar,USD,Elasticsearch;Microsoft SQL Server;MongoDB;MyS...,Elasticsearch;Microsoft SQL Server;MongoDB;MyS...,Academic researcher;Data scientist or machine ...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Industry that I’d be working in;Flex time or a...,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",C#;C++;Go;Julia;Python;Scala;SQL,Go;HTML/CSS;JavaScript;Julia;PHP;Python;R;Ruby...,Apache Spark;Hadoop;Keras;Pandas;TensorFlow;To...,Apache Spark;Hadoop;Keras;Pandas;TensorFlow;To...,"Github;Slack;Google Suite (Docs, Meet, etc)",Jira;Github;Slack;Microsoft Teams;Trello;Googl...,Yes,Extremely important,Somewhat important,Better compensation;Trouble with leadership at...,"Read company media, such as employee blogs or ...",Every few months,Not sure,No,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Indifferent,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,Windows,20 to 99 employees,AWS;Docker;Google Cloud Platform;iOS;Linux;MacOS,AWS;Docker;Google Cloud Platform;Linux;MacOS;W...,I have some influence,Straight / Heterosexual,Yes,Neutral,Less than once per month or monthly,Daily or almost daily,Easy,Appropriate in length,No,"A social science (such as anthropology, psycho...",Django;Flask,Django;Flask;jQuery,Somewhat more welcome now than last year,45.0,10,6
24097,I am a developer by profession,No,27.0,11,Weekly,110000.0,2000000.0,United States,United States dollar,USD,NaN,NaN,"Developer, back-end;Developer, embedded applic...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Woman,How widely used or impactful my work output wo...,Very dissatisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell,Bash/Shell/PowerShell;TypeScript,NaN,Ansible;Node.js,"Jira;Github;Slack;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Microsoft Teams;G...,Yes,Somewhat important,Fairly important,Having a bad day (or week or month) at work;Wa...,"Read company media, such as employee blogs or ...",Once a year,Not sure,No,Yes,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Panic;Watch help / tutori...,Linux-based,500 to 999 employees,AWS;Docker;Kubernetes;Linux;Raspberry Pi,Docker;Linux;Raspberry Pi,I have some influence,Bisexual,Yes,"Yes, somewhat",A few times per month or weekly,A few times per week,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;Angular.js,Just as welcome now as I felt last year,40.0,9,5
33886,I am a developer by profession,No,24.0,18,Weekly,110000.0,2000000.0,United States,United States dollar,USD,MariaDB,MariaDB;SQLite,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;JavaScript;Python;Ruby;R...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Node.js,Node.js;Unreal Engine,"Github;Slack;Trello;Google Suite (Docs, Meet, ...","Github;Gitlab;Slack;Trello;Google Suite (Docs,...",Yes,Extremely important,Very important,Better compensation;Looking to relocate,"Read company media, such as employee blogs or ...",Once a year,No,Yes,No,Never,NaN,Indifferent,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,MacOS,"1,000 to 4,999 employees",AWS,AWS,I have little or no influence,Straight / Heterosexual,No,"No, not really",NaN,A few times per month or weekly,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;React.js;Ruby on Rails,jQuery;React.js;Ruby on Rails,Just as welcome now as I felt last year,NaN,5,1
33745,I am a developer by profession,No,25.0,12,Weekly,60000.0,2000000.0,United States,United States dollar,USD,Firebase;MongoDB;SQLite,MongoDB;MySQL,"Developer, front-end","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,Southeast Asian,Woman,Flex time or a flexible schedule;Remote work o...,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",HTML/CSS;JavaScript,C++;HTML/CSS;Java;JavaScript;PHP;SQL,Node.js;Unity 3D;Unreal Engine,.NET,NaN,Jira;Github;Gitlab;Slack;Microsoft Teams,Not sure,Somewhat important,Very important,Better compensation;Better work/life balance;G...,"Read company media, such as employee blogs or ...",Once every few years,Not sure,Yes,No,Rarely: 1-2 days per year or less,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Panic;Do other work ...,MacOS,"10,000 or more employees",Docker;Google Cloud Platform;Heroku,AWS;Slack Apps and Integrations;WordPress,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",A few times per week,Multiple times per day,Easy,Too long,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Express;Gatsby,ASP.NET,Somewhat less welcome now than last year,40.0,8,3

In [10]:
# Rendezés fizetés és életkor szerint
df_survey.sort_values(by=['ConvertedComp', 'Age'], ascending=[False, True])

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
53443,I am a developer by profession,Yes,20.0,18,Weekly,55000.0,2000000.0,United States,United States dollar,USD,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...,Firebase;Microsoft SQL Server;MongoDB;MySQL;Or...,"Developer, back-end;Developer, front-end;Devel...","Secondary school (e.g. American high school, G...",Employed full-time,Hispanic or Latino/a/x,Man,"Languages, frameworks, and other technologies ...",Neither satisfied nor dissatisfied,I am actively looking for a job,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Python,C#;HTML/CSS;Java;JavaScript;Kotlin;Python,Flutter;Node.js;React Native,.NET;.NET Core;Flutter;Node.js;React Native;Un...,Github;Slack;Microsoft Azure;Google Suite (Doc...,Github;Slack;Microsoft Azure;Google Suite (Doc...,No,Extremely important,Somewhat important,Curious about other opportunities;Better work/...,Company reviews from third party sites (e.g. G...,Every few months,Not sure,Yes,No,Rarely: 1-2 days per year or less,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Go for a walk or other physical activity;Do ot...,MacOS,20 to 99 employees,Android;AWS;Google Cloud Platform;Heroku;iOS;L...,Microsoft Azure;Windows;WordPress,I have little or no influence,Straight / Heterosexual,Not sure/can't remember,Neutral,NaN,A few times per month or weekly,Easy,Appropriate in length,No,NaN,Angular;Angular.js;Django;Express;Flask;React....,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,40.0,1,1
58973,"I am not primarily a developer, but I write co...",No,21.0,15,Weekly,40000.0,2000000.0,United States,United States dollar,USD,Microsoft SQL Server;MySQL;SQLite,Microsoft SQL Server,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Specific department or team I’d be working on;...,Very dissatisfied,I am actively looking for a job,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,C#;HTML/CSS;JavaScript;SQL;VBA,.NET;.NET Core;Node.js;Xamarin,.NET;.NET Core,Jira;Github;Slack,Jira,No,Neutral,Fairly important,Having a bad day (or week or month) at work;Be...,Company reviews from third party sites (e.g. G...,Once a year,NaN,No,No,Often: 1-2 days per week or more,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow,Windows,20 to 99 employees,Android;Windows,AWS;Windows,I have little or no influence,Straight / Heterosexual,No,"No, not at all",NaN,Daily or almost daily,Easy,Appropriate in length,No,"Information systems, information technology, o...",ASP.NET;ASP.NET Core;React.js;Ruby on Rails,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,45.0,5,2
3620,I am a developer by profession,Yes,22.0,14,Weekly,70000.0,2000000.0,United States,United States dollar,USD,NaN,IBM DB2;MariaDB;Microsoft SQL Server;MongoDB;M...,"Developer, full-stack",Some college/university study without earning ...,Employed full-time,Hispanic or Latino/a/x,Man,Remote work options;Office environment or comp...,Very satisfied,I am not interested in new job opportunities,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,.NET;.NET Core;Unity 3D;Unreal Engine,Node.js;Pandas,NaN,Confluence;Jira;Github;Gitlab;Slack;Microsoft ...,Not sure,Neutral,Not at all important/not necessary,Better compensation;Better work/life balance;W...,"Read company media, such as employee blogs or ...",Every few months,Yes,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Do other work and come ba...,Windows,20 to 99 employees,NaN,Android;Docker;Linux;MacOS;Raspberry Pi;Window...,I have little or no influence,Straight / Heterosexual,Yes,"Yes, definitely",Daily or almost daily,Multiple times per day,Easy,Too short,No,"Computer science, computer engineering, or sof...",NaN,Django;Express;Flask;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,45.0,8,2
4791,I am a developer by profession,Yes,22.0,14,Weekly,70000.0,2000000.0,United States,United States dollar,USD,NaN,Oracle;Redis,"Developer, desktop or enterprise applications;...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Specific depa...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",Bash/Shell/PowerShell;C#;Go;Haskell;HTML/CSS;J...,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...,.NET;.NET Core;Unity 3D,.NET;.NET Core;Unity 3D,Github;Slack;Microsoft Teams,Github;Microsoft Teams,No,Somewhat important,Critically important,Having a bad day (or week or month) at work;Be...,Company reviews from third party sites (e.g. G...,Every few months,No,No,No,Occasionally: 1-2 days per quarter but less th...,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Play games;Call a coworker or friend;Visit Sta...,Windows,"5,000 to 9,999 employees",Docker;Kubernetes,Docker;Windows,I have little or no influence,Straight / Heterosexual,Yes,"No, not really",A few times per month or weekly,Multiple times per day,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",React.js,Angular.js;React.js;Spring,Just as welcome now as I felt last year,40.0,8,Less than 1 year
17900,"I am not primarily a developer, but I write co...",Yes,22.0,15,Weekly,80000.0,2000000.0,United States,United States dollar,USD,DynamoDB,DynamoDB,"Database administrator;Developer, back-end;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly dissatisfied,I am actively looking for a job,Kotlin;Scala;TypeScript,Java;JavaScript;TypeScript,Node.js;Teraform,Node.js;Teraform,Jira;Github;Slack;Trello,Confluence;Jira;Github;Slack;Trello,No,Extremely important,Very important,Just because;Having a bad day (or week or mont...,"Read company media, such as employee blogs or ...",Every few months,Yes,No,No,Sometimes: 1-2 days per month but less than we...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Watch help / tutorial vid...,Windows,"10,000 or more employees",AWS;Docker;Kubernetes,AWS;Slack Apps and Integrations,I have a great deal of influence,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Multiple times per day,Easy,Too long,No,Mathematics or statistics,Angular;Express;Spring,Angular;Express;Vue.js,Somewhat more welcome now than last year,40.0,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [11]:
# Hiányzó értékek kezelése rendezéskor
df_survey.sort_values(by='ConvertedComp', ascending=False, na_position='last')

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18770,I am a developer by profession,Yes,31.0,19,Weekly,75000.0,2000000.0,United States,United States dollar,USD,NaN,Microsoft SQL Server,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,Flex time or a flexible schedule;Remote work o...,Very satisfied,I am not interested in new job opportunities,Rust;Swift,C#;HTML/CSS;JavaScript;SQL;TypeScript,TensorFlow;Teraform;Xamarin,.NET;.NET Core,NaN,Github;Microsoft Teams;Microsoft Azure;Trello;...,No,Extremely important,Fairly important,Better compensation;Trouble with my teammates;...,"Read company media, such as employee blogs or ...",Once a year,Not sure,Yes,No,Occasionally: 1-2 days per quarter but less th...,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,20 to 99 employees,NaN,Microsoft Azure,I have some influence,Straight / Heterosexual,Yes,"No, not really",A few times per week,Multiple times per day,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",NaN,Angular;ASP.NET;ASP.NET Core;jQuery;React.js,Just as welcome now as I felt last year,40.0,11,9
65527,I am a developer by profession,Yes,NaN,11,Monthly,450000.0,2000000.0,United States,United States dollar,USD,Firebase;IBM DB2;MongoDB;PostgreSQL,DynamoDB;Firebase;Microsoft SQL Server;MongoDB...,Data scientist or machine learning specialist;...,Some college/university study without earning ...,Employed part-time,NaN,NaN,Industry that I’d be working in;Remote work op...,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",HTML/CSS;JavaScript;Kotlin;Python;Ruby;SQL;Typ...,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,NaN,NaN,NaN,NaN,Yes,Somewhat important,Fairly important,Having a bad day (or week or month) at work;Wa...,Company reviews from third party sites (e.g. G...,Once every few years,Yes,Yes,No,Rarely: 1-2 days per year or less,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,100 to 499 employees,Android;AWS;Google Cloud Platform;IBM Cloud or...,Android;AWS;Heroku;Microsoft Azure;Windows,NaN,NaN,Yes,Neutral,Less than once per month or monthly,A few times per month or weekly,NaN,NaN,NaN,"Information systems, information technology, o...",Angular;Django;Express;React.js;Ruby on Rails;...,Django;Express;Flask;React.js;Spring,Just as welcome now as I felt last year,60.0,14,3
18688,I am a developer by profession,Yes,25.0,21,Weekly,90000.0,2000000.0,United States,United States dollar,USD,Firebase;PostgreSQL,MySQL,"Developer, back-end;Developer, front-end;Devel...",Some college/university study without earning ...,Employed full-time,White or of European descent,Man,Diversity of the company or organization;How w...,Slightly dissatisfied,I am actively looking for a job,C#,HTML/CSS;JavaScript;PHP;SQL,.NET Core;Flutter;TensorFlow,React Native,NaN,Github,No,NaN,Fairly important,Wanting to share accomplishments with a wider ...,Company reviews from third party sites (e.g. G...,Every few months,No,Onboarding? What onboarding?,Yes,Often: 1-2 days per week or more,Ask developers I know/work with;Visit develope...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Watch help / tutorial vid...,Windows,2 to 9 employees,NaN,Linux,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, somewhat",Daily or almost daily,Multiple times per day,Easy,Appropriate in length,No,I never declared a major,ASP.NET Core,React.js,Just as welcome now as I felt last year,40.0,6,5
65502,I am a developer by profession,Yes,NaN,11,Weekly,66000.0,2000000.0,United States,United States dollar,USD,Microsoft SQL Server;MongoDB,MariaDB;Microsoft SQL Server;MongoDB;PostgreSQL,"Database administrator;Developer, back-end;Dev...","Associate degree (A.A., A.S., etc.)",Employed full-time,NaN,NaN,Flex time or a flexible schedule;Specific depa...,Neither satisfied nor dissatisfied,I am not interested in new job opportunities,C#;Perl;Python,C#;HTML/CSS;JavaScript;Perl;Python;SQL;TypeScript,.NET Core;Node.js,.NET;.NET Core;Node.js;Xamarin,Github;Microsoft Teams;Microsoft Azure,Confluence;Jira;Github;Microsoft Teams;Microso...,Not sure,Somewhat important,Very important,Just because;Having a bad day (or week or mont...,"Read company media, such as employee blogs or ...",Once a year,No,Onboarding? What onboarding?,No,Sometimes: 1-2 days per month but less than we...,NaN,Annoyed,Stack Overflow (public Q&A for anyone who code...,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,100 to 499 employees,Microsoft Azure;Raspberry Pi,Microsoft Azure;Raspberry Pi;Windows,I have little or no influence,NaN,Yes,"Yes, somewhat",A few times per week,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;Flask;Vue.js,ASP.NET;ASP.NET Core;Express;Flask;Gatsby;Reac...,Just as welcome now as I felt last year,40.0,5,3
42919,I am a developer by profession,Yes,NaN,15,Weekly,135000.0,2000000.0,United States,United States dollar,USD,Cassandra;Elasticsearch;MariaDB;MongoDB,MySQL,"Developer, back-end;Developer, desktop or ente...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",NaN,NaN,Flex time or a flexible schedule;Financial per...,Very satisfied,"I’m not actively looking, but I am open to new...",C#;Go;Rust;TypeScript,Go;Java;SQL,.NET Core;Apache Spark;Hadoop;React Native,NaN,NaN,NaN,No,Extremely important,Fairly important,Curious about other opportunities;Better compe...,Company reviews from third party sites (e.g. G...,Once a year,Not sure,Onboarding? What onboarding?,No,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,NaN,"10,000 or more employees",Android;AWS;Docker;iOS;Kubernetes;MacOS;Raspbe...,Docker;Linux;Windows,NaN,NaN,Not sure/can't remember,Neutral,NaN,Daily or almost daily,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",Angular,Spring,Just as welcome now as I felt last year,42.0,13,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [12]:
df_survey.loc[filter_high_salary, ['Country', 'ConvertedComp']].sort_values(
    by='ConvertedComp', ascending=False).head(10)

                  Country  ConvertedComp
Respondent
29260       United States      2000000.0
33865       United States      2000000.0
16018       United States      2000000.0
193         United States      2000000.0
3948        United States      2000000.0
33787       United States      2000000.0
4027        United States      2000000.0
24097       United States      2000000.0
33886       United States      2000000.0
33745       United States      2000000.0

In [13]:
filter_hungary = df_survey['Country'] == 'Hungary'

In [14]:
df_survey.loc[filter_hungary, ['Age', 'DevType', 'LanguageWorkedWith', 'ConvertedComp']].sort_values(
    by='ConvertedComp', ascending=False).head(30)

,Age,DevType,LanguageWorkedWith,ConvertedComp
Respondent,,,,
54198,38.0,Data or business analyst;Data scientist or mac...,Bash/Shell/PowerShell;C++;HTML/CSS;Java;JavaSc...,250000.0
46816,NaN,"Developer, back-end;Developer, full-stack;Educ...",NaN,230916.0
17411,37.0,"Developer, back-end;Developer, front-end;Devel...",HTML/CSS;JavaScript;Ruby;SQL,135123.0
13612,NaN,"Developer, full-stack",C#;JavaScript;SQL;TypeScript,129720.0
7033,22.0,"Developer, mobile",Objective-C;Swift,124800.0
16126,44.0,Academic researcher;Data or business analyst;D...,Bash/Shell/PowerShell;Julia;Python,111341.0
59482,33.0,"Developer, back-end",Dart;HTML/CSS;Java;JavaScript;Kotlin;SQL,90804.0
50680,29.0,"Developer, full-stack;Developer, mobile",Dart;HTML/CSS;JavaScript;Kotlin;Objective-C;Py...,90000.0
13242,35.0,"Developer, back-end;Developer, desktop or ente...",Assembly;Java;Python;SQL,78912.0
12431,38.0,"Developer, full-stack",Go;HTML/CSS;JavaScript;Python;Scala,76971.0
48454,27.0,"Developer, back-end",C++;Python;SQL,76968.0
21968,41.0,"Developer, back-end",Java;SQL,75000.0
34534,40.0,"Developer, back-end;Developer, desktop or ente...",Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,71196.0
35232,30.0,"Developer, back-end;Developer, front-end;Devel...",Java,69276.0
34639,33.0,"Developer, back-end;Developer, desktop or ente...",C#;HTML/CSS;JavaScript;TypeScript,69276.0
23559,41.0,"Developer, back-end;Developer, front-end;Devel...",C#;HTML/CSS;Python;SQL,69276.0
31002,27.0,"Developer, front-end;Developer, full-stack",HTML/CSS;JavaScript;PHP;Ruby;TypeScript,69183.0
15603,34.0,"Developer, back-end;Developer, front-end;Devel...",HTML/CSS;Kotlin,65425.0
13343,40.0,"Developer, back-end;Developer, desktop or ente...",Bash/Shell/PowerShell;C++;Java;Scala,65424.0
12991,38.0,"Database administrator;Developer, back-end;Dev...",HTML/CSS;Java;JavaScript;PHP;SQL;TypeScript,64150.0
5350,43.0,"Designer;Developer, back-end;Developer, deskto...",C#;HTML/CSS;TypeScript,64143.0
56115,34.0,Data or business analyst;Database administrato...,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,64143.0
1346,22.0,"Developer, back-end;Developer, desktop or ente...",C#;HTML/CSS;JavaScript;SQL;TypeScript,64000.0
59428,34.0,"Developer, back-end;Developer, desktop or ente...",Bash/Shell/PowerShell;C;C#;C++;HTML/CSS;JavaSc...,57732.0
15940,34.0,Data scientist or machine learning specialist;...,Bash/Shell/PowerShell;C#;Go;HTML/CSS;JavaScrip...,55907.0
18579,36.0,"Developer, back-end;Developer, full-stack;DevO...",Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,55800.0
25166,27.0,"Developer, back-end;Developer, embedded applic...",Go;Java;SQL,53880.0
12350,NaN,"Developer, back-end;Developer, front-end;Devel...",Bash/Shell/PowerShell;HTML/CSS;JavaScript;Kotl...,53880.0
8844,36.0,"Developer, back-end",Bash/Shell/PowerShell;JavaScript,53496.0
45167,NaN,"Developer, mobile",C#;HTML/CSS;Java;JavaScript;Kotlin;Swift;TypeS...,53184.0

In [15]:
filter_python = df_survey['LanguageWorkedWith'].str.contains('Python', na=False)

In [16]:
df_survey.loc[filter_python, 'LanguageWorkedWith'].sort_values(
    ascending=False).head(10).str.split(';').str[0].value_counts().head(10)

LanguageWorkedWith
Python    10
Name: count, dtype: int64